### ISSUE TITLE
resolution off for browser instance

### ISSUE THREAD

**Issue by marclave** [steel-dev/steel-browser#3]
seems like its zoomed in? this is what it looks like on my mac running `14.3.1`

<img width="1036" alt="image" src="https://github.com/user-attachments/assets/c50072a4-45ad-46b5-920d-4a2f5273245f">

**Comment by fukouda** [comment]
Gonna take a look at this over the weekend, good catch

**Comment by fukouda** [comment]
Was super delayed on this but should be fixed by #25 !
